### ISSUE TITLE
Feedback form on website is broken

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/oursite#224]
See https://github.com/foundersandcoders/mail-fac/issues/4

**Comment by iteles** [comment]
Can we ask someone in FAC7 to take this on?

**Comment by iteles** [comment]
If not, a super short term solution is to remove the form and replace with text to email us.

**Comment by sofer** [comment]
Thank you @oturnermajor. Let me know if you have any questions.

**Comment by oturnermajor** [comment]
@sofer @iteles [Submitted a PR](https://github.com/foundersandcoders/mail-fac/pull/5)

Hope I've done this right! I followed the website code and ended up on this [mail-fac](https://github.com/foundersandcoders/mail-fac) repo which seemed to have the relevant stuff on.

Went for mailgun because the code for it was already set up & dependencies installed (and 10,000 emails/month seems like enough!) :)

Once the PR is merged all we need to do is **make sure there's a mailgun API key in the heroku env variables**.

**Comment by sofer** [comment]
Working. Belatedly closing. Thank you @oturnermajor.
