### ISSUE TITLE
Addition of part-time programme application for Nazareth

### ISSUE THREAD

**Issue by rebeccaradding** [foundersandcoders/oursite#364]
@des-des , it looks like one way to drum up enough interest in the programme among local applicants will be to run Coding for Everyone style sessions several times a week in Nazareth in January/February. A lot of people we've met are interested in the idea of changing careers but are struggling with a full-time commitment.

I'm creating a pull request for it now and I'm going to assign it to you, but would like to discuss this with you first.

**Comment by des-des** [comment]
@rebeccaradding This sounds like a good idea. I guess the main problem here is actually building the course, there is a need for this in London as well. One idea could be to use the full time curriculum, and give people 2x time to complete. Or we could only teach client-side or something.

Once I am in Nazareth I will be more than happy to organise lots of meetups, including a regular one for people learning. I think the problem here is planning / decision time. If we are offering something that we call a part time course then we need to create it first ... Between now and jan my main priority is building the curriculum for the full-time course. Can you give me more detail on what how you see a part time course working?

I am also happy to skype (today or wednesday/thursday next week)
